#############################################################################
# Makefile for building: client
# Generated by qmake (2.01a) (Qt 4.8.1) on: Tue Sep 24 15:58:37 2013
# Project:  ../packet_client_Qt/client.pro
# Template: app
# Command: /usr/bin/qmake -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile ../packet_client_Qt/client.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I../packet_client_Qt -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I../packet_client_Qt -I. -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib/i386-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = ../packet_client_Qt/contentwidget.cpp \
		../packet_client_Qt/main.cpp \
		../packet_client_Qt/mainwidget.cpp \
		../packet_client_Qt/mypushbutton.cpp \
		../packet_client_Qt/skinwidget.cpp \
		../packet_client_Qt/statuswidget.cpp \
		../packet_client_Qt/sysbutton.cpp \
		../packet_client_Qt/titlewidget.cpp \
		../packet_client_Qt/toolbutton.cpp \
		../packet_client_Qt/toolwidget.cpp moc_contentwidget.cpp \
		moc_mainwidget.cpp \
		moc_mypushbutton.cpp \
		moc_skinwidget.cpp \
		moc_statuswidget.cpp \
		moc_sysbutton.cpp \
		moc_titlewidget.cpp \
		moc_toolbutton.cpp \
		moc_toolwidget.cpp \
		qrc_src.cpp
OBJECTS       = contentwidget.o \
		main.o \
		mainwidget.o \
		mypushbutton.o \
		skinwidget.o \
		statuswidget.o \
		sysbutton.o \
		titlewidget.o \
		toolbutton.o \
		toolwidget.o \
		moc_contentwidget.o \
		moc_mainwidget.o \
		moc_mypushbutton.o \
		moc_skinwidget.o \
		moc_statuswidget.o \
		moc_sysbutton.o \
		moc_titlewidget.o \
		moc_toolbutton.o \
		moc_toolwidget.o \
		qrc_src.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/declarative_debug.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		../packet_client_Qt/client.pro
QMAKE_TARGET  = client
DESTDIR       = 
TARGET        = client

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)
	{ test -n "$(DESTDIR)" && DESTDIR="$(DESTDIR)" || DESTDIR=.; } && test $$(gdb --version | sed -e 's,[^0-9]\+\([0-9]\)\.\([0-9]\).*,\1\2,;q') -gt 72 && gdb --nx --batch --quiet -ex 'set confirm off' -ex "save gdb-index $$DESTDIR" -ex quit '$(TARGET)' && test -f $(TARGET).gdb-index && objcopy --add-section '.gdb_index=$(TARGET).gdb-index' --set-section-flags '.gdb_index=readonly' '$(TARGET)' '$(TARGET)' && rm -f $(TARGET).gdb-index || true

Makefile: ../packet_client_Qt/client.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/declarative_debug.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/i386-linux-gnu/libQtGui.prl \
		/usr/lib/i386-linux-gnu/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile ../packet_client_Qt/client.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/declarative_debug.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/i386-linux-gnu/libQtGui.prl:
/usr/lib/i386-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile ../packet_client_Qt/client.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/client1.0.0 || $(MKDIR) .tmp/client1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/client1.0.0/ && $(COPY_FILE) --parents ../packet_client_Qt/contentwidget.h ../packet_client_Qt/mainwidget.h ../packet_client_Qt/mypushbutton.h ../packet_client_Qt/skinwidget.h ../packet_client_Qt/statuswidget.h ../packet_client_Qt/sysbutton.h ../packet_client_Qt/titlewidget.h ../packet_client_Qt/toolbutton.h ../packet_client_Qt/toolwidget.h .tmp/client1.0.0/ && $(COPY_FILE) --parents ../packet_client_Qt/src.qrc .tmp/client1.0.0/ && $(COPY_FILE) --parents ../packet_client_Qt/contentwidget.cpp ../packet_client_Qt/main.cpp ../packet_client_Qt/mainwidget.cpp ../packet_client_Qt/mypushbutton.cpp ../packet_client_Qt/skinwidget.cpp ../packet_client_Qt/statuswidget.cpp ../packet_client_Qt/sysbutton.cpp ../packet_client_Qt/titlewidget.cpp ../packet_client_Qt/toolbutton.cpp ../packet_client_Qt/toolwidget.cpp .tmp/client1.0.0/ && (cd `dirname .tmp/client1.0.0` && $(TAR) client1.0.0.tar client1.0.0 && $(COMPRESS) client1.0.0.tar) && $(MOVE) `dirname .tmp/client1.0.0`/client1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/client1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_contentwidget.cpp moc_mainwidget.cpp moc_mypushbutton.cpp moc_skinwidget.cpp moc_statuswidget.cpp moc_sysbutton.cpp moc_titlewidget.cpp moc_toolbutton.cpp moc_toolwidget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_contentwidget.cpp moc_mainwidget.cpp moc_mypushbutton.cpp moc_skinwidget.cpp moc_statuswidget.cpp moc_sysbutton.cpp moc_titlewidget.cpp moc_toolbutton.cpp moc_toolwidget.cpp
moc_contentwidget.cpp: ../packet_client_Qt/contentwidget.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) ../packet_client_Qt/contentwidget.h -o moc_contentwidget.cpp

moc_mainwidget.cpp: ../packet_client_Qt/mainwidget.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) ../packet_client_Qt/mainwidget.h -o moc_mainwidget.cpp

moc_mypushbutton.cpp: ../packet_client_Qt/mypushbutton.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) ../packet_client_Qt/mypushbutton.h -o moc_mypushbutton.cpp

moc_skinwidget.cpp: ../packet_client_Qt/skinwidget.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) ../packet_client_Qt/skinwidget.h -o moc_skinwidget.cpp

moc_statuswidget.cpp: ../packet_client_Qt/statuswidget.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) ../packet_client_Qt/statuswidget.h -o moc_statuswidget.cpp

moc_sysbutton.cpp: ../packet_client_Qt/sysbutton.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) ../packet_client_Qt/sysbutton.h -o moc_sysbutton.cpp

moc_titlewidget.cpp: ../packet_client_Qt/titlewidget.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) ../packet_client_Qt/titlewidget.h -o moc_titlewidget.cpp

moc_toolbutton.cpp: ../packet_client_Qt/toolbutton.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) ../packet_client_Qt/toolbutton.h -o moc_toolbutton.cpp

moc_toolwidget.cpp: ../packet_client_Qt/toolwidget.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) ../packet_client_Qt/toolwidget.h -o moc_toolwidget.cpp

compiler_rcc_make_all: qrc_src.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_src.cpp
qrc_src.cpp: ../packet_client_Qt/src.qrc \
		../packet_client_Qt/img/sysButton/sys_button_close.png \
		../packet_client_Qt/img/sysButton/sys_button_min.png \
		../packet_client_Qt/img/sysButton/title_bar_menu.png \
		../packet_client_Qt/img/sysButton/SkinButton.png \
		../packet_client_Qt/img/sysButton/sys_button_max.png \
		../packet_client_Qt/icon/e.png \
		../packet_client_Qt/icon/b9.jpg \
		../packet_client_Qt/icon/l.png \
		../packet_client_Qt/icon/penguin.png \
		../packet_client_Qt/icon/b3.jpg \
		../packet_client_Qt/icon/f.png \
		../packet_client_Qt/icon/b4small.jpg \
		../packet_client_Qt/icon/m.png \
		../packet_client_Qt/icon/b8small.jpg \
		../packet_client_Qt/icon/b4.jpg \
		../packet_client_Qt/icon/g.png \
		../packet_client_Qt/icon/b9small.jpg \
		../packet_client_Qt/icon/n.png \
		../packet_client_Qt/icon/a.png \
		../packet_client_Qt/icon/b5.jpg \
		../packet_client_Qt/icon/b1small.jpg \
		../packet_client_Qt/icon/h.png \
		../packet_client_Qt/icon/o.png \
		../packet_client_Qt/icon/b5small.jpg \
		../packet_client_Qt/icon/b.png \
		../packet_client_Qt/icon/penguin3.png \
		../packet_client_Qt/icon/b6.jpg \
		../packet_client_Qt/icon/i.png \
		../packet_client_Qt/icon/p.png \
		../packet_client_Qt/icon/qt-logo.png \
		../packet_client_Qt/icon/c.png \
		../packet_client_Qt/icon/b2small.jpg \
		../packet_client_Qt/icon/b7.jpg \
		../packet_client_Qt/icon/j.png \
		../packet_client_Qt/icon/b6small.jpg \
		../packet_client_Qt/icon/b1.jpg \
		../packet_client_Qt/icon/d.png \
		../packet_client_Qt/icon/b8.jpg \
		../packet_client_Qt/icon/k.png \
		../packet_client_Qt/icon/b3small.jpg \
		../packet_client_Qt/icon/penguintvicon.png \
		../packet_client_Qt/icon/b2.jpg \
		../packet_client_Qt/icon/b7small.jpg
	/usr/bin/rcc -name src ../packet_client_Qt/src.qrc -o qrc_src.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

contentwidget.o: ../packet_client_Qt/contentwidget.cpp ../packet_client_Qt/contentwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o contentwidget.o ../packet_client_Qt/contentwidget.cpp

main.o: ../packet_client_Qt/main.cpp ../packet_client_Qt/mainwidget.h \
		../packet_client_Qt/statuswidget.h \
		../packet_client_Qt/titlewidget.h \
		../packet_client_Qt/toolwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o ../packet_client_Qt/main.cpp

mainwidget.o: ../packet_client_Qt/mainwidget.cpp ../packet_client_Qt/mainwidget.h \
		../packet_client_Qt/titlewidget.h \
		../packet_client_Qt/toolwidget.h \
		../packet_client_Qt/statuswidget.h \
		../packet_client_Qt/contentwidget.h \
		../packet_client_Qt/skinwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwidget.o ../packet_client_Qt/mainwidget.cpp

mypushbutton.o: ../packet_client_Qt/mypushbutton.cpp ../packet_client_Qt/mypushbutton.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mypushbutton.o ../packet_client_Qt/mypushbutton.cpp

skinwidget.o: ../packet_client_Qt/skinwidget.cpp ../packet_client_Qt/skinwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o skinwidget.o ../packet_client_Qt/skinwidget.cpp

statuswidget.o: ../packet_client_Qt/statuswidget.cpp ../packet_client_Qt/statuswidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o statuswidget.o ../packet_client_Qt/statuswidget.cpp

sysbutton.o: ../packet_client_Qt/sysbutton.cpp ../packet_client_Qt/sysbutton.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sysbutton.o ../packet_client_Qt/sysbutton.cpp

titlewidget.o: ../packet_client_Qt/titlewidget.cpp ../packet_client_Qt/titlewidget.h \
		../packet_client_Qt/sysbutton.h \
		../packet_client_Qt/mypushbutton.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o titlewidget.o ../packet_client_Qt/titlewidget.cpp

toolbutton.o: ../packet_client_Qt/toolbutton.cpp ../packet_client_Qt/toolbutton.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o toolbutton.o ../packet_client_Qt/toolbutton.cpp

toolwidget.o: ../packet_client_Qt/toolwidget.cpp ../packet_client_Qt/toolwidget.h \
		../packet_client_Qt/toolbutton.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o toolwidget.o ../packet_client_Qt/toolwidget.cpp

moc_contentwidget.o: moc_contentwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_contentwidget.o moc_contentwidget.cpp

moc_mainwidget.o: moc_mainwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwidget.o moc_mainwidget.cpp

moc_mypushbutton.o: moc_mypushbutton.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mypushbutton.o moc_mypushbutton.cpp

moc_skinwidget.o: moc_skinwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_skinwidget.o moc_skinwidget.cpp

moc_statuswidget.o: moc_statuswidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_statuswidget.o moc_statuswidget.cpp

moc_sysbutton.o: moc_sysbutton.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_sysbutton.o moc_sysbutton.cpp

moc_titlewidget.o: moc_titlewidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_titlewidget.o moc_titlewidget.cpp

moc_toolbutton.o: moc_toolbutton.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_toolbutton.o moc_toolbutton.cpp

moc_toolwidget.o: moc_toolwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_toolwidget.o moc_toolwidget.cpp

qrc_src.o: qrc_src.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_src.o qrc_src.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

