#############################################################################
# Makefile for building: 360
# Generated by qmake (2.01a) (Qt 4.8.1) on: Mon Jun 17 22:18:14 2013
# Project:  360.pro
# Template: app
# Command: /usr/bin/qmake -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile 360.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib/i386-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = contentwidget.cpp \
		main.cpp \
		mainwidget.cpp \
		mypushbutton.cpp \
		skinwidget.cpp \
		statuswidget.cpp \
		sysbutton.cpp \
		titlewidget.cpp \
		toolbutton.cpp \
		toolwidget.cpp moc_contentwidget.cpp \
		moc_mainwidget.cpp \
		moc_mypushbutton.cpp \
		moc_skinwidget.cpp \
		moc_statuswidget.cpp \
		moc_sysbutton.cpp \
		moc_titlewidget.cpp \
		moc_toolbutton.cpp \
		moc_toolwidget.cpp \
		qrc_src.cpp
OBJECTS       = contentwidget.o \
		main.o \
		mainwidget.o \
		mypushbutton.o \
		skinwidget.o \
		statuswidget.o \
		sysbutton.o \
		titlewidget.o \
		toolbutton.o \
		toolwidget.o \
		moc_contentwidget.o \
		moc_mainwidget.o \
		moc_mypushbutton.o \
		moc_skinwidget.o \
		moc_statuswidget.o \
		moc_sysbutton.o \
		moc_titlewidget.o \
		moc_toolbutton.o \
		moc_toolwidget.o \
		qrc_src.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/declarative_debug.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		360.pro
QMAKE_TARGET  = 360
DESTDIR       = 
TARGET        = 360

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)
	{ test -n "$(DESTDIR)" && DESTDIR="$(DESTDIR)" || DESTDIR=.; } && test $$(gdb --version | sed -e 's,[^0-9]\+\([0-9]\)\.\([0-9]\).*,\1\2,;q') -gt 72 && gdb --nx --batch --quiet -ex 'set confirm off' -ex "save gdb-index $$DESTDIR" -ex quit '$(TARGET)' && test -f $(TARGET).gdb-index && objcopy --add-section '.gdb_index=$(TARGET).gdb-index' --set-section-flags '.gdb_index=readonly' '$(TARGET)' '$(TARGET)' && rm -f $(TARGET).gdb-index || true

Makefile: 360.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/declarative_debug.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/i386-linux-gnu/libQtGui.prl \
		/usr/lib/i386-linux-gnu/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile 360.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/declarative_debug.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/i386-linux-gnu/libQtGui.prl:
/usr/lib/i386-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile 360.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/3601.0.0 || $(MKDIR) .tmp/3601.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/3601.0.0/ && $(COPY_FILE) --parents contentwidget.h mainwidget.h mypushbutton.h skinwidget.h statuswidget.h sysbutton.h titlewidget.h toolbutton.h toolwidget.h .tmp/3601.0.0/ && $(COPY_FILE) --parents src.qrc .tmp/3601.0.0/ && $(COPY_FILE) --parents contentwidget.cpp main.cpp mainwidget.cpp mypushbutton.cpp skinwidget.cpp statuswidget.cpp sysbutton.cpp titlewidget.cpp toolbutton.cpp toolwidget.cpp .tmp/3601.0.0/ && (cd `dirname .tmp/3601.0.0` && $(TAR) 3601.0.0.tar 3601.0.0 && $(COMPRESS) 3601.0.0.tar) && $(MOVE) `dirname .tmp/3601.0.0`/3601.0.0.tar.gz . && $(DEL_FILE) -r .tmp/3601.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_contentwidget.cpp moc_mainwidget.cpp moc_mypushbutton.cpp moc_skinwidget.cpp moc_statuswidget.cpp moc_sysbutton.cpp moc_titlewidget.cpp moc_toolbutton.cpp moc_toolwidget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_contentwidget.cpp moc_mainwidget.cpp moc_mypushbutton.cpp moc_skinwidget.cpp moc_statuswidget.cpp moc_sysbutton.cpp moc_titlewidget.cpp moc_toolbutton.cpp moc_toolwidget.cpp
moc_contentwidget.cpp: contentwidget.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) contentwidget.h -o moc_contentwidget.cpp

moc_mainwidget.cpp: mainwidget.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mainwidget.h -o moc_mainwidget.cpp

moc_mypushbutton.cpp: mypushbutton.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mypushbutton.h -o moc_mypushbutton.cpp

moc_skinwidget.cpp: skinwidget.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) skinwidget.h -o moc_skinwidget.cpp

moc_statuswidget.cpp: statuswidget.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) statuswidget.h -o moc_statuswidget.cpp

moc_sysbutton.cpp: sysbutton.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) sysbutton.h -o moc_sysbutton.cpp

moc_titlewidget.cpp: titlewidget.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) titlewidget.h -o moc_titlewidget.cpp

moc_toolbutton.cpp: toolbutton.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) toolbutton.h -o moc_toolbutton.cpp

moc_toolwidget.cpp: toolwidget.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) toolwidget.h -o moc_toolwidget.cpp

compiler_rcc_make_all: qrc_src.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_src.cpp
qrc_src.cpp: src.qrc \
		img/sysButton/sys_button_close.png \
		img/sysButton/sys_button_min.png \
		img/sysButton/title_bar_menu.png \
		img/sysButton/SkinButton.png \
		img/sysButton/sys_button_max.png \
		icon/e.png \
		icon/b9.jpg \
		icon/l.png \
		icon/penguin.png \
		icon/b3.jpg \
		icon/f.png \
		icon/b4small.jpg \
		icon/m.png \
		icon/b8small.jpg \
		icon/b4.jpg \
		icon/g.png \
		icon/b9small.jpg \
		icon/n.png \
		icon/a.png \
		icon/b5.jpg \
		icon/b1small.jpg \
		icon/h.png \
		icon/o.png \
		icon/b5small.jpg \
		icon/b.png \
		icon/penguin3.png \
		icon/b6.jpg \
		icon/i.png \
		icon/p.png \
		icon/qt-logo.png \
		icon/c.png \
		icon/b2small.jpg \
		icon/b7.jpg \
		icon/j.png \
		icon/b6small.jpg \
		icon/b1.jpg \
		icon/d.png \
		icon/b8.jpg \
		icon/k.png \
		icon/b3small.jpg \
		icon/penguintvicon.png \
		icon/b2.jpg \
		icon/b7small.jpg
	/usr/bin/rcc -name src src.qrc -o qrc_src.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

contentwidget.o: contentwidget.cpp contentwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o contentwidget.o contentwidget.cpp

main.o: main.cpp mainwidget.h \
		statuswidget.h \
		titlewidget.h \
		toolwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwidget.o: mainwidget.cpp mainwidget.h \
		titlewidget.h \
		toolwidget.h \
		statuswidget.h \
		contentwidget.h \
		skinwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwidget.o mainwidget.cpp

mypushbutton.o: mypushbutton.cpp mypushbutton.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mypushbutton.o mypushbutton.cpp

skinwidget.o: skinwidget.cpp skinwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o skinwidget.o skinwidget.cpp

statuswidget.o: statuswidget.cpp statuswidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o statuswidget.o statuswidget.cpp

sysbutton.o: sysbutton.cpp sysbutton.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sysbutton.o sysbutton.cpp

titlewidget.o: titlewidget.cpp titlewidget.h \
		sysbutton.h \
		mypushbutton.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o titlewidget.o titlewidget.cpp

toolbutton.o: toolbutton.cpp toolbutton.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o toolbutton.o toolbutton.cpp

toolwidget.o: toolwidget.cpp toolwidget.h \
		toolbutton.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o toolwidget.o toolwidget.cpp

moc_contentwidget.o: moc_contentwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_contentwidget.o moc_contentwidget.cpp

moc_mainwidget.o: moc_mainwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwidget.o moc_mainwidget.cpp

moc_mypushbutton.o: moc_mypushbutton.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mypushbutton.o moc_mypushbutton.cpp

moc_skinwidget.o: moc_skinwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_skinwidget.o moc_skinwidget.cpp

moc_statuswidget.o: moc_statuswidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_statuswidget.o moc_statuswidget.cpp

moc_sysbutton.o: moc_sysbutton.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_sysbutton.o moc_sysbutton.cpp

moc_titlewidget.o: moc_titlewidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_titlewidget.o moc_titlewidget.cpp

moc_toolbutton.o: moc_toolbutton.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_toolbutton.o moc_toolbutton.cpp

moc_toolwidget.o: moc_toolwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_toolwidget.o moc_toolwidget.cpp

qrc_src.o: qrc_src.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_src.o qrc_src.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

